language: node_js
node_js:
- v7
os: osx
osx_image: xcode8
cache:
  directories:
  - node_modules
install:
- yarn --pure-lockfile
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
before_install:
- brew update
- brew install yarn
- export TZ=Australia/Sydney
script:
- npm test
- npm run release
