language: node_js
node_js:
- v6
addons:
  apt:
    packages:
    - xvfb
install:
- npm install &>/dev/null
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
before_install:
- export TZ=Australia/Sydney
script:
- git config --global user.email "wbwilliam7@gmail.com"
- git config --global user.name "willyb321"
- npm test
- electron-packager . --platform=darwin --arch=x64
- cd /home/travis/build/willyb321/electron-menubar-timetable/TimeTable-darwin-x64/
- zip -r -q TimeTable.zip *
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: 0JOU1MGxICDnNDE8DUr7R6DR+iSa2xSvz0jPNNv7qKpWxZ7Au4ECUNvrlVp74JBKsfUTXduMH5EBHnyt9rJieAhqQJPudi+2mviHeZFyJWo+crsn0qb/bXjD2iqbm2FalKTBtshIXN8HcV/Kfz7RAbZOHAmZCljLShvF2Klr4tpMtn6pnr2ReavUglNtNPC2F2mGa6pAVV+MJbc8/SJ/Go2gTLRyt6KTBhsjvdCESIDqHjRTedH00ZxzuFIrrSWThpuDVPkKV8rCjtOHUBWAPEHj5lG2K1kQAe6HEobt1N6Y78jYkb9GKDSsgKHjQ0bmd1YbwS3voE11EbNenPBVkh0n3kM/4o1eKjUG4kW56LnVBzRtY18NCJW8WMbet4BW0NMT5aqJDqmtOj48SPh0GLZoT1bvh5ZGHr6IQHie3e1mUqGrOWJL97MHNckMrBod1d5GUq7otf0O8BA6+qtvZ0aC+Wx2Lrrd3wsvXsOjkZ4wzzBR2qjztcnKNzPNBJcnwbbyYi7i0p8rnS3caFcD29Kqq4yXCaq8J6KC6S9cFEpKdmofrrMh0zsXSPpB7yscRCf7TOn8lHwsHQ6Jhdjy6OQMzoVJW6hZpOg/D7I1GbDUleqC0aF1mGM11ZfKDZLy4R8WQ1yFtZvaMhGf2F4l8m+f97t1WFFpl5UnCl8f0Hc=
  file: /home/travis/build/willyb321/electron-menubar-timetable/TimeTable-darwin-x64/TimeTable.zip
  on:
    tags: false
    repo: willyb321/electron-menubar-timetable
  provider: bintray
  file: ../bintraydescriptor.json
  user: willyb321
  key:
    secure: ZfrFXsc3nyjZIDKeB3vRyVaSvPOqErH+JdN9+gj9YLJDbFr0TMiFGwe64LfOySpH/K+Icq9+o6bHVXh6WW9YumPDdgGgxtIOcpzV/45WRE4JSUWcAyC5Uoy1xeK1pG0TwedJ/dRX8Byg/ZzMAO5MI7qH7NPNHszlhBJGMn4D0E9Q6x1j1mFT/649ToBR9IUF331BsgzqPg6Ubg43sIrQUA3YToaJmykeGUWkK6bfQ2Uc0snLy/qWFEN4t1ZcbK/rTCUCgSAfNFVcjcguUFmXmUyT3lobWCr1tlUQ2vCJj8Cx2fRaBN67/eywQTxPy1vbx2b/wmwJaQCsnvFZ2FLUf11e1PLolej0ZHB7gj26apfNZCjrlpktRhUFc8Whdg1PSchRGSCrVA+oFQ5VXfFO3ZS0m0uYPnsE/Rlik+t20FTftPnkUvpkW3sbErB3ZWDgKHoVnxyPUo0C20DvE7YxL+fxH3rAlN7rai4XhwSCESAcZ9Sbw2pGVha0uWgyrOjz0PouOOmvNZh9RZnPTpfetMHSIeasp5ircbgV4J37vSf8K6B17r41fa6jm/61lJYmOyV05P5+c2E4wrm19vG/ztt7kRW93IupfzxHKcKHQDs1fZ6Wh/E+2ByTthgg5iAVnyvnb1VO2KE7SOuypdZ2jkQ3oC6W3YAsJxqJCj0Mbl0=
branches:
  except:
  - /^*-v[0-9]/
after_success:
- export GIT_TAG=build-$TRAVIS_BUILD_NUMBER-$TRAVIS_BRANCH-$(date "+%Y-%m-%d-%I-%M")
- git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
- git push origin $GIT_TAG
