language: node_js
node_js:
  - v6
  - v5
  - v4
  - '0.12'
  - '0.10'
addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
