osx_image: xcode7.3

sudo: required
dist: trusty

language: c

matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
cache:
  directories:
  - node_modules
  - $HOME/.electron
  - $HOME/.cache


addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
install:
- yarn
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
before_install:
- nvm install 7
- npm install -g yarn
- export TZ=Australia/Sydney
script:
- npm test
- npm run release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
